[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = [
    "node_modules/pdfkit/js/data/**",
    "node_modules/pdfkit/js/data/*.afm",
    "node_modules/pdfkit/js/font/data/**",
    "node_modules/pdfkit/**/*"
  ]



[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
